import React from 'react';
import nextId from 'react-id-generator';
import { Tabs } from 'antd';

import {
  Sort,
  UserActivity,
  UserCollectibles,
  UserCreated,
  UserFollower,
  UserFollowing,
  UserLiked,
  UserOnSale,
} from '../../components/organisms';

const { TabPane } = Tabs;
const sortTypes = ['Recommended', 'Most Recent', 'Popular', 'Price High', 'Price Low', 'text'];
const sort = <Sort items={sortTypes} onChange={() => {}} />;
const User: React.FC = () => {
  return (
    // TODO:autogenerated key
    <div className="user">
      <div className="row">
        <Tabs tabBarExtraContent={sort} className="tabs">
          <TabPane tab="On sale" key={nextId()}>
            <UserOnSale />
          </TabPane>
          <TabPane tab="Collectibles" key={nextId()}>
            <UserCollectibles />
          </TabPane>
          <TabPane tab="Created" key={nextId()}>
            <UserCreated />
          </TabPane>
          <TabPane tab="Liked" key={nextId()}>
            <UserLiked />
          </TabPane>
          <TabPane tab="Activity" key={nextId()}>
            <UserActivity />
          </TabPane>
          <TabPane tab="Following" key={nextId()}>
            <UserFollowing />
          </TabPane>
          <TabPane tab="Follower" key={nextId()}>
            <UserFollower />
          </TabPane>
        </Tabs>
      </div>
    </div>
  );
};

export default User;
