import React from 'react';
import nextId from 'react-id-generator';
import { Tabs } from 'antd';

import userAvatar from '../../assets/img/mock/user-avatar.png';
import { UserOverview } from '../../components/molecules';
import { UserOverviewProps } from '../../components/molecules/UserOverview';
import {
  Sort,
  UserActivity,
  UserCollectibles,
  UserCreated,
  UserFollower,
  UserFollowing,
  UserLiked,
  UserOnSale,
} from '../../components/organisms';

import './User.scss';

const mockUser: UserOverviewProps = {
  avatarSrc: userAvatar,
  name: "Satoshi's Mom",
  wallet: '0x3d6a89c8751a462363563723776193',
  description: `T3 "Skelly" Series, 1 off a kind numbered skulls will drop and none will ever be repeated, each Skelly will either have a new colorway, or animation, sometimes both. Which Skelly will be the Chosen one. `,
  socialNetworks: [
    { networkType: 'Instagram', link: 'https://www.instagram.com/thejuze/', name: 'thejuze' },
    { networkType: 'Facebook', link: 'https://www.instagram.com/thejuze/', name: 'theJuze' },
  ],
};

const { TabPane } = Tabs;
const sortTypes = ['Recommended', 'Most Recent', 'Popular', 'Price High', 'Price Low', 'text'];
const sort = <Sort items={sortTypes} onChange={() => {}} />;
const User: React.FC = () => {
  return (
    // TODO:autogenerated key
    <div className="user">
      <div className="row">
        <div className="user__cap">Img</div>
      </div>
      <div className="row">
        <UserOverview
          name={mockUser.name}
          wallet={mockUser.wallet}
          avatarSrc={mockUser.avatarSrc}
          description={mockUser.description}
          socialNetworks={mockUser.socialNetworks}
        />
      </div>
      <div className="row">
        <Tabs tabBarExtraContent={sort} className="tabs">
          <TabPane tab="On sale" key={nextId()}>
            <UserOnSale />
          </TabPane>
          <TabPane tab="Collectibles" key={nextId()}>
            <UserCollectibles />
          </TabPane>
          <TabPane tab="Created" key={nextId()}>
            <UserCreated />
          </TabPane>
          <TabPane tab="Liked" key={nextId()}>
            <UserLiked />
          </TabPane>
          <TabPane tab="Activity" key={nextId()}>
            <UserActivity />
          </TabPane>
          <TabPane tab="Following" key={nextId()}>
            <UserFollowing />
          </TabPane>
          <TabPane tab="Follower" key={nextId()}>
            <UserFollower />
          </TabPane>
        </Tabs>
      </div>
    </div>
  );
};

export default User;
